# Variables to be set:
# SERIAL_NUMBER, SENSOR, PROJECT_DIR, DATE

# SITE AND INSTRUMENT
instrument_number: SN%SERIAL_NUMBER%
site_name: %SENSOR_ID%
site_abbrev: %SENSOR_ID%
start_date:
end_date:
coords:
    lat: %COORDINATES_LAT%
    lon: %COORDINATES_LON%
    alt: %COORDINATES_ALT%
coord_file:
utc_offset: %UTC_OFFSET%

# BEHAVIOUR
min_interferogram_size: 1.6
start_with_spectra: False
delete_abscosbin_files: True
delete_input_files: False
note:
proffast_path: %PROFFAST_PATH%

# TCCON
tccon_mode: False
tccon_setting:

# INPUT PATHS
interferogram_path: %PROJECT_DIR%/inputs/%CONTAINER_ID%/%SENSOR_ID%_ifg
map_path: %PROJECT_DIR%/inputs/%CONTAINER_ID%/%SENSOR_ID%_map
pressure_path: %PROJECT_DIR%/inputs/%CONTAINER_ID%/%SENSOR_ID%_pressure
pressure_type_file: %PROJECT_DIR%/inputs/%CONTAINER_ID%/%SENSOR_ID%-log-format.yml

# OUTPUT PATHS
analysis_path: %PROJECT_DIR%/outputs/analysis
result_path: %PROJECT_DIR%/outputs
